name: Helm & Helmfile Action
description: Setup Helm and plugins, update repositories and applies configuration
author: dapi
branding:
  icon: anchor
  color: blue
inputs:
  args:
    description: Helmfile command arguments
    required: false
  #command:
    #default: apply
    #description: Helmfile command arguments
    #required: false
  #environment:
    #default: ''
    #description: Helmfile environment
    #required: false
outputs: {}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args: ${{ inputs.args }}
    #- ${{ inputs.command }}
    #- "-e"
    #- ${{ inputs.environment }}
